# Generated by Django 3.1.1 on 2020-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0004_auto_20200924_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comedy'), (4, 'Family'), (5, 'Sci-Fi'), (3, 'Horror'), (2, 'Action'), (6, 'Fantasy'), (0, 'Other'), (7, 'Drama')], default=0),
        ),
    ]
