# Generated by Django 3.1.1 on 2020-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0007_auto_20200928_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Fantasy'), (5, 'Sci-Fi'), (7, 'Drama'), (1, 'Comedy'), (4, 'Family'), (0, 'Other'), (2, 'Action'), (3, 'Horror')], default=0),
        ),
    ]
