# Generated by Django 3.1.1 on 2020-09-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0009_auto_20200928_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Family'), (3, 'Horror'), (6, 'Fantasy'), (0, 'Other'), (1, 'Comedy'), (5, 'Sci-Fi'), (7, 'Drama'), (2, 'Action')], default=0),
        ),
    ]
