# Generated by Django 3.1.1 on 2020-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0025_auto_20200928_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Action'), (7, 'Drama'), (4, 'Family'), (0, 'Other'), (3, 'Horror'), (1, 'Comedy'), (5, 'Sci-Fi'), (6, 'Fantasy')], default=0),
        ),
    ]
