# Generated by Django 3.1.1 on 2020-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0026_auto_20200928_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Sci-Fi'), (3, 'Horror'), (0, 'Other'), (2, 'Action'), (1, 'Comedy'), (6, 'Fantasy'), (4, 'Family'), (7, 'Drama')], default=0),
        ),
    ]
