# Generated by Django 3.1.1 on 2020-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0031_auto_20200928_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (5, 'Sci-Fi'), (7, 'Drama'), (6, 'Fantasy'), (1, 'Comedy'), (3, 'Horror'), (2, 'Action'), (4, 'Family')], default=0),
        ),
    ]
