# Generated by Django 3.1.1 on 2020-09-28 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmscore', '0032_auto_20200928_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genres',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Drama'), (1, 'Comedy'), (0, 'Other'), (2, 'Action'), (6, 'Fantasy'), (5, 'Sci-Fi'), (4, 'Family'), (3, 'Horror')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('year_of_birth', models.DateField(default=datetime.date.today)),
                ('films', models.ManyToManyField(to='filmscore.Film')),
            ],
        ),
    ]
